server:
  port: 8905
spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/di-invincible/springcloud-config
          username: 111
          password: 111
          clone-on-start: true #开启启动时直接从git获取配置
  security: #配置用户名和密码
    user:
      name: admin
      password: 123456




eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8001/eureka/
    registry-fetch-interval-seconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
  instance:
    lease-expiration-duration-in-seconds: 15  # 发呆时间，15秒不发送就过期 即服务续约到期时间（缺省为90s）
    lease-renewal-interval-in-seconds: 5   #心跳时间，5秒发送一次心跳（缺省为30s
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
