server:
  port: 9401
spring:
  application:
    name: oauth2-service
  redis: #redis\u76F8\u5173\u914D\u7F6E
#    password: lanlinker789*** #\u6709\u5BC6\u7801\u65F6\u8BBE\u7F6E
#    port: 6379
#    host: 192.168.1.36
#    password: lanlinker789*** #\u6709\u5BC6\u7801\u65F6\u8BBE\u7F6E
    port: 6379
    host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8001/eureka/
    registry-fetch-interval-seconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
  instance:
    lease-expiration-duration-in-seconds: 15  # 发呆时间，15秒不发送就过期 即服务续约到期时间（缺省为90s）
    lease-renewal-interval-in-seconds: 5   #心跳时间，5秒发送一次心跳（缺省为30s
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
