
server:
  port: 10020

spring:
  application:
    name: gateway
  profiles:
    include: route
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@192.168.1.116:10010/eureka/,http://root:root@192.168.1.132:10010/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
