server:
  port: 8701
spring:
  application:
    name: feign-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8001/eureka/
    registry-fetch-interval-seconds: 5 #\u8868\u793Aeureka client\u95F4\u9694\u591A\u4E45\u53BB\u62C9\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3A30\u79D2
  instance:
    lease-expiration-duration-in-seconds: 15  # \u53D1\u5446\u65F6\u95F4\uFF0C15\u79D2\u4E0D\u53D1\u9001\u5C31\u8FC7\u671F \u5373\u670D\u52A1\u7EED\u7EA6\u5230\u671F\u65F6\u95F4\uFF08\u7F3A\u7701\u4E3A90s\uFF09
    lease-renewal-interval-in-seconds: 5   #\u5FC3\u8DF3\u65F6\u95F4\uFF0C5\u79D2\u53D1\u9001\u4E00\u6B21\u5FC3\u8DF3\uFF08\u7F3A\u7701\u4E3A30s
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


feign:
  hystrix:
    enabled: true #\u5728Feign\u4E2D\u5F00\u542FHystrix
  compression:
    request:
      enabled: false #\u662F\u5426\u5BF9\u8BF7\u6C42\u8FDB\u884CGZIP\u538B\u7F29
      mime-types: text/xml,application/xml,application/json #\u6307\u5B9A\u538B\u7F29\u7684\u8BF7\u6C42\u6570\u636E\u7C7B\u578B
      min-request-size: 2048 #\u8D85\u8FC7\u8BE5\u5927\u5C0F\u7684\u8BF7\u6C42\u4F1A\u88AB\u538B\u7F29
    response:
      enabled: false #\u662F\u5426\u5BF9\u54CD\u5E94\u8FDB\u884CGZIP\u538B\u7F29
logging:
  level:
    com.example.feignservice.feign: debug
