server:
  port: 10011

spring:
  application:
    name: eureka-server2
  security:
    user:
      name: root
      password: root
eureka:
#  instance:
#    hostname: eureka2 #eureka服务端的实例名称
  client:
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://localhost:10010/eureka/
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
