server:
  port: 10010

spring:
  application:
    name: xkit-java-springcloud-eureka
  security:
    user:
      name: root
      password: root


eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}