spring:
  application:
    name: eureka-server-cluster
  security:
    user:
      name: root
      password: root
  profiles:
    active: node1


eureka:
  client:
    register-with-eureka: false # 表示是否注册自身到eureka服务器  由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    fetch-registry: false #是否从eureka上获取注册信息  由于注册中心的职责就是维护服务实例, 并不需要检索服务, 所以也设置为 false