server:
  port: 8201
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_example?useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 0.1 #设置Sleuth的抽样收集概率

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' #暴露hystrix监控端点

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8001/eureka/
    registry-fetch-interval-seconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
  instance:
    lease-expiration-duration-in-seconds: 15  # 发呆时间，15秒不发送就过期 即服务续约到期时间（缺省为90s）
    lease-renewal-interval-in-seconds: 5   #心跳时间，5秒发送一次心跳（缺省为30s
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
