server:
  port: 8201
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.105.132:3306/lanlinker-labor?useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: lanlinker666

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

