server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #\u914D\u7F6E\u5B58\u50A8\u914D\u7F6E\u4FE1\u606F\u7684Git\u4ED3\u5E93
          uri: https://gitee.com/di-invincible/springcloud-config
          username: 11
          password: 11
          clone-on-start: true #\u5F00\u542F\u542F\u52A8\u65F6\u76F4\u63A5\u4ECEgit\u83B7\u53D6\u914D\u7F6E


eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8001/eureka/
    registry-fetch-interval-seconds: 5 #\u8868\u793Aeureka client\u95F4\u9694\u591A\u4E45\u53BB\u62C9\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3A30\u79D2
  instance:
    lease-expiration-duration-in-seconds: 15  # \u53D1\u5446\u65F6\u95F4\uFF0C15\u79D2\u4E0D\u53D1\u9001\u5C31\u8FC7\u671F \u5373\u670D\u52A1\u7EED\u7EA6\u5230\u671F\u65F6\u95F4\uFF08\u7F3A\u7701\u4E3A90s\uFF09
    lease-renewal-interval-in-seconds: 5   #\u5FC3\u8DF3\u65F6\u95F4\uFF0C5\u79D2\u53D1\u9001\u4E00\u6B21\u5FC3\u8DF3\uFF08\u7F3A\u7701\u4E3A30s
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
